# Loki configuration for noteparser log aggregation

# Server configuration
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s

# Authentication (disabled for internal use)
auth_enabled: false

# Ingester configuration
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal
    checkpoint_duration: 5m
    flush_on_shutdown: true
    replay_memory_ceiling: 1GB

# Schema configuration
schema_config:
  configs:
    - from: 2023-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/index_cache
    shared_store: filesystem
    cache_ttl: 24h
    resync_interval: 5m
  filesystem:
    directory: /loki/chunks

# Compactor
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 5m

# Limits configuration
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  max_streams_per_user: 10000
  max_line_size: 256KB
  max_entries_limit_per_query: 10000
  max_chunks_per_query: 2000000
  max_query_series: 500
  cardinality_limit: 100000
  max_concurrent_tail_requests: 10
  retention_period: 30d

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 0s

# Table manager configuration
table_manager:
  retention_deletes_enabled: true
  retention_period: 30d

# Query range configuration
query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      memcached_client:
        consistent_hash: true
        addresses: memcached:11211
        timeout: 500ms

# Frontend configuration
frontend:
  max_outstanding_per_tenant: 256
  compress_responses: true
  log_queries_longer_than: 5s

# Querier configuration
querier:
  query_timeout: 1m
  tail_max_duration: 1h
  extra_query_delay: 0s
  query_ingesters_within: 2h
  engine:
    timeout: 3m
    max_look_back_period: 30s

# Query scheduler configuration
query_scheduler:
  max_outstanding_requests_per_tenant: 256

# Ruler configuration (for alerts)
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /tmp/loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: inmemory
  enable_api: true
  enable_alertmanager_v2: true

# Analytics configuration
analytics:
  reporting_enabled: false

# Common configuration
common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

# Memberlist configuration (for clustering)
memberlist:
  join_members: []
  abort_if_cluster_join_fails: false
  bind_port: 7946
  gossip_interval: 2s
  gossip_nodes: 2
  gossip_to_dead_nodes_time: 30s
  push_pull_interval: 30s